### ISSUE TITLE
defined_tags_json is not working properly when defined as variable

### ISSUE THREAD

**Issue by luckeyca** [hashicorp/packer-plugin-oracle#120]
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

When defining the "defined_tags_json" as variable with value specified in either "default" or in separate value file, it doesn't work. However, the same value, if hard-coded in the builder script, it works.

#### Reproduction Steps
1. create builder script using hcl2 syntax and hard-code the defined_tag_json in the build script as below.
```
packer {
  required_plugins {
    oracle = {
      source  = "github.com/hashicorp/oracle"
      version = ">= 1.1.0, < 2.0.0"
    }
  }
}

source "oracle-oci" "this" {
....
  defined_tags_json = jsonencode({
    "Operations" = {
      "Environment" = "prod"
      "Team"        = "CostCenter"
    }
  })
...
}
```
2. run packer init and then validate. This will work without issue.
3. change the script above to use variable as defined_tags_json = jsonencode(var.defined_tags_json) and defined variable with default value as bleow
```
variable "defined_tags_json" {
  type        = string
  description = "JSON string to add one or more defined tags for a given namespace to the resulting custom image. Only works on HCL2 templates."
  default     = "{
    "Operations" = {
      "Environment" = "prod"
      "Team"        = "CostCenter"
    }
  }"
}

OR as one-liner below
variable "defined_tags_json" {
  type        = string
  description = "JSON string to add one or more defined tags for a given namespace to the resulting custom image. Only works on HCL2 templates."
  default     = "{ "Operations" = { "Environment" = "prod" "Team"  = "CostCenter" } }"
}

```
4. packer validate will fail

### Plugin and Packer version

From `packer version`

Packer v1.11.0
Plugin version: v1.1.0

### Simplified Packer Buildfile

If the file is longer than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/) of the log or use the [Github detailed
format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d)
instead of posting it directly in the issue.

### Operating system and Environment details

OS, Architecture, and any other information you can provide about the
environment.

Ubuntu 22.04 x86

### Log Fragments and crash.log files

Include appropriate log fragments. If the log is longer than a few dozen lines,
please include the URL to the [gist](https://gist.github.com/) of the log or
use the [Github detailed format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d) instead of posting it directly in the issue.

Set the env var `PACKER_LOG=1` for maximum log detail.

**Comment by lbajolet-hashicorp** [comment]
Hi @luckeyca,

Could you share the error you get when validating the template with `packer validate`?

From what I see, this looks like a usage problem here; the `jsonencode` function accepts any type of object that HCL lets you express. If you write a JSON string that is invalid, it will be rejected either at serialisation, or at deserialisation.
If I had to guess, serialising a string will work (and add the required escaping characters to the output), but deserialising it into the expected structure will fail as the model doesn't match (i.e. `map[string]map[string]interface{}` in this case). You should see a `Failed to unmarshal 'defined_tags'` error then.

You can pass in a valid JSON string as-is to the data here, which can be defined in a variable, but it needs to be valid JSON, otherwise you'll end-up with the same problem.
From the looks of it, your variables might work, but you shouldn't pass them through `jsonencode` if passing a raw JSON serialised object.

Let me know if that helps!

**Comment by luckeyca** [comment]
Hi @lbajolet-hashicorp, not sure we are on the same page for this problem. As my example above, when hard-coding the json string in the .pkr.hcl code block itself inside the jsonencode function, everything works fine. However, if I need to make defined_tag_json a variable and put the variable value either as default value or in a separate var-file, that's when it fails. If you believe it's usage problem. could you please give an example how to put the json string as variable default value and in a separate var-file which is where I am stuck. Also on the side note, given on OCI, in terraform and old json packer syntax, all tags and defined_tags are map object, also in the hcl2 packer code, it's converting json string back to map. Would you agree that it doesn't make sense to set the defined tags using json string to begin with given map object has been working fine, easy and consistent across the board?

**Comment by lbajolet-hashicorp** [comment]
So to be explicit, `defined_tags_json` takes a string as parameter; this is because the HCL2/cty type system will be limiting otherwise, as the underlying type is a `map[string]map[string]object`, and the way `object` is defined in HCL2, it needs a schema for its content. Maybe there's something we can do to make it possible for those to be a plain object, but it's not crystal clear to me how to do this now.

Minor technicality here though: `jsonencode` accepts any `cty` object to work, but free-form values are harder to explicit with the type system we have (refer to the [Type Constraints](https://developer.hashicorp.com/packer/docs/templates/hcl_templates/variables#type-constraints) documentation on this). We should probably revisit this later, but in the meantime we're stuck with what we have, so we need to play nice with it.

Given that the result is meant to be a string, I would suggest going with a string variable, but without passing it through `jsonencode`, as it will not produce a value that will be compatible with the structure expected for the tags.

If you want to use a variable with a default value here, you have two choices that come to mind.

1. You can use `jsonencode` as the default value with a free-form object. The function accepts virtually anything, so that should work as expected for the default case. As for later uses, my advice would be to provide a serialised JSON value that conforms to the structure I suggested above. So basically an object that contains those values. Typically in your varfile, you could have something like:

```hcl
# HCL template
variable "defined_tags_json" {
  type = "string"
  default = jsonencode({
    "Operations" = {
      "Environment" = "dev"
      "Team"        = "Development"
    }
  })
}

source "oracle-oci" "example" {
  defined_tags_json = var.defined_tags_json
}

# Varfile
defined_tags_json = "{\"Operations\":{\"Environment\":\"prod\",\"Team\":\"CostCenter\"}}"
```

2. If you don't need more than two levels of nesting here though (and given this is a tag repo I would think this might be enough), you can go with a variable typed as `map(map(string))`, and pass it through `jsonencode` then. So the variable would be defined as:

```hcl
# HCL template
variable "defined_tags_json" {
  type = map(map(string))
  default = {
    "Operations" = {
      "Environment" = "dev"
      "Team"        = "Development"
    }
  }
}

source "oracle-oci" "example" {
  defined_tags_json = jsonencode(var.defined_tags_json)
}

# Varfile
defined_tags_json = {
  "Operations" = {
    "Environment" = "prod"
    "Team"        = "CostCenter"
  }
}
```

Hope that helps!

Note: I haven't tested those templates as I'd need more things to have the validation pass, but I would think these two alternatives would work.

**Comment by luckeyca** [comment]
Hi @lbajolet-hashicorp, thanks for the quick response. for the reasoning to change the defined_tag from map(packer json syntax) to json string(packer hcl2 syntax) still doesn't make any sense because the tag argument stays the same as map object between packer json syntax and hcl2 syntax. So, there is really no reason I can think of why defined_tag variable type has to changed.

As for the examples you provided, I believe I tested those before and none of those worked, I will test them again tomorrow and let you know the results.

**Comment by lbajolet-hashicorp** [comment]
The reason why the types are different is because there's no way with the HCL2 grammar to express a free-form object in a schema, that's the only reason why this is a string, as we have the expressiveness to define the argument as such.
JSON is unencumbered by this technicality, as objects (`interface{}` in Go), are able to be serialised/deserialised, which is not the case for HCL2, I invite you to refer to the [comment by Martin](https://github.com/hashicorp/hcl/issues/291#issuecomment-496347585) regarding this.

The arguments between JSON and HCL are different for the configuration here, in JSON you would use `defined_tags` (defined as a `map[string]map[string]interface{}`, whereas in HCL2 you would have to use `defined_tags_json` (defined as a `string`, implied to be valid serialised JSON), since the former is ignored in HCL2 mode, because of the deserialisation of `interface{}` as pointed out in the related comment.
Now the comment in question is a bit old, and maybe things have changed regarding HCL schemas and the ability to deserialise as any free-form structure may be a thing, but we haven't looked into it yet.

**Comment by luckeyca** [comment]
interesting. then why the "tag" argument can still stay the same and be map of string variable type between json syntax and hcl2 syntax?

**Comment by lbajolet-hashicorp** [comment]
Hi @luckeyca,

`tags` is a `map[string]string`, no `interface{}` in there, so everything is accurately defined, it doesn't need to change.
The plugin's maintained by us (Hashicorp), with a best effort level of commitment: i.e. we continue pushing updates to make it work with Packer as the main product evolves, we keep an eye on issues/PRs and continue performing the releases, but feature requests and other changes are not a priority for us.

Yeah regarding 1a that's on me, it cannot work as `default` for variables needs to be a literal value, and no functions are exposed at this point yet (can't remember why that was, but there's a technical reason iirc).

Good to know that the other solutions did the trick.
It appears to me that this is solved, as such I'll close this issue now. I'll also close #121 as this cannot be addressed in the current state of our grammar, and workarounds do exist. It may not be too intuitive to come-up with those though, so we'll have an internal discussion to figure out how to best document this for other users.

Please feel free to reopen if you think I pulled the trigger too early on this.
Thanks!

**Comment by luckeyca** [comment]
Hi @lbajolet-hashicorp, thanks a lot for all the detailed explanations and solutions. The only thing left from this, since I didn't see you mentioned, is to correct the misleading documentation that says defined_tag_json can only be string type in HCL2 template which evidently it's not the case.

**Comment by lbajolet-hashicorp** [comment]
I'm not sure where the misunderstanding lies, the `defined_tag_json` attribute is effectively a `string`, hence why you have to `jsonencode` your payload if it's not already a valid JSON-serialised object as a string.
If anything, the documentation doesn't do justice to the `defined_tag` attribute, as it's not a `map[string]map[string]string`, but a `map[string]map[string]interface{}`, so the documentation clamps down what it accepts. I suspect this is because the documentation generator doesn't process the type properly and simplifies it too much, which is probably something to fix within the SDK's generation toolchain.

**Comment by luckeyca** [comment]
Hi @lbajolet-hashicorp, yes. It's more on how the text is to be understood as it's written. To the un-trained eyes(I am not go developer), as the documentation states like this, I would thought I could only define defined_tags_json as "string" type in the variable which was what gave me trouble because if the documentation changes from "defined_tags_json (string)" to "defined_tags_json (string/map of map of strings)", then it will be crystal clear. 

Also, given from end-user perspective, it just works the same as in the old json template, it doesn't really need to change the name from defined_tags to defined_tags_json, just use defined_tags(map of map of strings) to be consistent with how we have been using terraform and the old packer json template. It's more of end-user experience, again from a non-Go developer background. 

Then as in your example in solution 1b, given all those ESCAPEs when defined as "string", it's not really user-friendly to use it, especially when there are more tags involved. So, for simplicity sake, for HCL2, it can just be "defined_tags(map of map of strings), which would be exactly consistent across the board.  just my thought. Thanks again for all your help! :)
